#include "PythonGenerator.h"
#include <iostream>
#include <fstream>
#include <cctype>
#include <algorithm>
#include <stack>
#include <vector>
using namespace std;

PythonGenerator::PythonGenerator(const vector<string>& polish)
    : polishCode(polish), indentLevel(1), labelCounter(0) {
    collectVariables();
}

PythonGenerator::~PythonGenerator() {}

string PythonGenerator::newLabel() {
    return "label" + to_string(++labelCounter);
}

void PythonGenerator::collectVariables() {
    for (const auto& item : polishCode) {
        size_t pos = item.find(" := ");
        if (pos != string::npos) {
            string var = item.substr(0, pos);
            while (!var.empty() && var.back() == ' ') var.pop_back();
            if (var[0] != 't' && var != "t1" && var != "t2" && var != "t3") {
                variables.insert(var);
            }
        }
    }
}

string PythonGenerator::getIndent() {
    return string(indentLevel * 4, ' ');
}

string PythonGenerator::generate() {
    stringstream ss;

    ss << "# -*- coding: utf-8 -*-" << endl;
    ss << "# Generated by Pascal to Python Compiler" << endl;
    ss << endl;

    for (const auto& var : variables) {
        ss << var << " = 0" << endl;
    }
    if (!variables.empty()) ss << endl;

    ss << "def main():" << endl;
    indentLevel = 1;

    vector<string> outputLines;
    bool inLoopBody = false;
    string loopCondition = "";
    vector<string> loopBody;

    for (size_t i = 0; i < polishCode.size(); i++) {
        const string& item = polishCode[i];

        if (item.size() > 1 && item.back() == ':' && item[0] == 'L') {
            if (inLoopBody) {
                if (!loopCondition.empty()) {
                    outputLines.push_back(getIndent() + "while " + loopCondition + ":");
                    indentLevel++;
                    for (const auto& bodyLine : loopBody) {
                        outputLines.push_back(getIndent() + bodyLine);
                    }
                    indentLevel--;
                    loopBody.clear();
                }
                inLoopBody = false;
            }
            continue;
        }

        if (item.find(" := ") != string::npos && item[0] == 't') {
            size_t pos = item.find(" := ");
            string right = item.substr(pos + 4);
            while (!right.empty() && right.back() == ' ') right.pop_back();
            if (right.find(">") != string::npos ||
                right.find("<") != string::npos ||
                right.find("=") != string::npos) {
                loopCondition = right;
            }
            continue;
        }

        if (item.substr(0, 8) == "if_false") {
            inLoopBody = true;
            continue;
        }

        if (inLoopBody) {
            if (item.substr(0, 4) == "goto") continue;

            if (item.find(" := ") != string::npos) {
                size_t pos = item.find(" := ");
                string left = item.substr(0, pos);
                string right = item.substr(pos + 4);
                while (!left.empty() && left.back() == ' ') left.pop_back();
                while (!right.empty() && right.back() == ' ') right.pop_back();

                if (left[0] != 't') {
                    if (right[0] == 't') {
                        for (const auto& prev : polishCode) {
                            if (prev.find(right + " := ") != string::npos) {
                                size_t eqPos = prev.find(" := ");
                                if (eqPos != string::npos) {
                                    string expr = prev.substr(eqPos + 4);
                                    while (!expr.empty() && expr.back() == ' ') expr.pop_back();
                                    right = expr;
                                    break;
                                }
                            }
                        }
                    }
                    loopBody.push_back(left + " = " + right);
                }
                continue;
            }

            if (item == "write") {
                loopBody.push_back("print(x)");
                continue;
            }
            continue;
        }

        if (item.find(" := ") != string::npos) {
            size_t pos = item.find(" := ");
            string left = item.substr(0, pos);
            string right = item.substr(pos + 4);
            while (!left.empty() && left.back() == ' ') left.pop_back();
            while (!right.empty() && right.back() == ' ') right.pop_back();

            if (left[0] != 't') {
                outputLines.push_back(getIndent() + left + " = " + right);
            }
            continue;
        }

        if (item == "write") {
            outputLines.push_back(getIndent() + "print(x)");
            continue;
        }
    }

    if (inLoopBody && !loopCondition.empty()) {
        outputLines.push_back(getIndent() + "while " + loopCondition + ":");
        indentLevel++;
        for (const auto& bodyLine : loopBody) {
            outputLines.push_back(getIndent() + bodyLine);
        }
        indentLevel--;
    }

    for (const auto& line : outputLines) {
        ss << line << endl;
    }

    ss << endl;
    ss << "if __name__ == '__main__':" << endl;
    ss << "    main()" << endl;

    return ss.str();
}

bool PythonGenerator::saveToFile(const string& filename) {
    string code = generate();

    ofstream file(filename);
    if (!file.is_open()) {
        cerr << "Error: Cannot open file " << filename << " for writing" << endl;
        return false;
    }
    file << code;
    file.close();
    cout << "Python code saved to " << filename << endl;
    return true;
}